[package]
name = "hipblas-sys"
version = "0.1.0"
authors = ["charles-r-earp <charles.r.earp@gmail.com>"]
edition = "2018"
links = "hipblas"

[dependencies]
libc = "0.2.74"

[build-dependencies]
bindgen = { version = "0.54.1", optional = true }
